# Generated by Django 3.2.7 on 2021-10-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('ftname', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=12)),
                ('mob', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('edu', models.CharField(max_length=10)),
                ('college_name', models.CharField(max_length=30)),
                ('board', models.CharField(max_length=30)),
                ('percentage', models.CharField(max_length=10)),
                ('pic', models.FileField(max_length=50, upload_to='')),
                ('sign', models.FileField(max_length=50, upload_to='')),
                ('applieddate', models.CharField(max_length=12)),
                ('approve_status', models.CharField(max_length=10)),
            ],
        ),
    ]
